scrape_configs:
  - job_name: ckagent
    static_configs:
      - targets: ['192.168.1.11:9110']
        labels: {host: "debian-server", ip: "192.168.1.11"}

  - job_name: ckapi
    static_configs:
      - targets: ['192.168.1.11:9120']
        labels: {host: "debian-server", ip: "192.168.1.11"}
